config/routes.rb
Rails.application.routes.draw do
  root to: "flats#index"
  resources :flats
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def edit
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-6">
      <%= simple_form_for(@restaurant) do |f| %>
        <%= f.input :name %>
        <%= f.input :address %>
        <%= f.input :description %>
        <%= f.input :price_per_night %>
        <%= f.input :number_of_guests %>
        <%= f.submit class: "btn btn-primary"%>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/edit.html.erb
<h1>Flats#edit</h1>
<p>Find me in app/views/flats/edit.html.erb</p>

app/views/flats/index.html.erb
<h1>All our Flats (<%= Flat.count %>)</h1>

<% @flats.each do |flat| %>
  <div class="card">
    <p><%= flat.name %></p>
    <p><%= flat.address %></p>
    <div class="flexbox">
      <p><%= flat.number_of_guests %></p>
      <p><%= flat.price_per_night %></p>
    </div>
    <div class="bottom_card">
      <%= link_to "More info", flat_path(flat.id) %>
    </div>
  </div>
<% end %>

app/views/flats/new.html.erb
<h1>New flat</h1>

<%= render "form" %>

app/views/flats/show.html.erb
<h1><%= @flat.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="banner">
      <div class="flexbox">
        <%= link_to "Simple Airbnb", flats_path %>
        <%= link_to "Add Flat", new_flat_path %>
      </div>
    </div>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>